###
### Makefile for Gerp Project
###
### Author:  Danielle Jacobs

## Note, you do NOT need rules for
## FSTree.o and DirNode.o as those (pre-compiled) object files are 
## provided to you.
## 
## At the end, you can delete this comment
## 

CXX      = clang++
CXXFLAGS = -g3 -Wall -Wextra -Wpedantic -Wshadow
LDFLAGS  = -g3 

gerp: gerp.o main.o structs.o processing.o DirNode.o FSTree.o
	$(CXX) $(CXXFLAGS) -o gerp gerp.o main.o structs.o processing.o \
	DirNode.o FSTree.o

main.o: main.cpp gerp.h
	$(CXX) $(CXXFLAGS) -c main.cpp

gerp.o: gerp.cpp gerp.h processing.o structs.o
	$(CXX) $(CXXFLAGS) -c gerp.cpp

processing.o: processing.cpp FSTree.o DirNode.o
	$(CXX) $(CXXFLAGS) -c processing.cpp FSTree.o DirNode.o

structs.o: structs.cpp processing.h
	$(CXX) $(CXXFLAGS) -c structs.cpp processing.h

processing_unit_tests.o: processing_unit_tests.cpp processing.h
	$(CXX) $(CXXFLAGS) -c processing_unit_tests.cpp

processing_unit_tests: processing_unit_tests.o processing.o
	$(CXX) $(CXXFLAGS) -o processing_unit_tests processing_unit_tests.o \
	processing.o DirNode.o FSTree.o
##
## Here is a special rule that removes all .o files besides the provided ones 
## (DirNode.o and FSTree.o), all temporary files (ending with ~), and 
## a.out produced by running unit_test. First, we find all .o files 
## that are not provided files, then we run rm -f on each found file 
## using the -exec find flag. Second, we delete the temporary files
## and a.out. @ is used to suppress stdout.
## 
## You do not need to modify or further comment this rule!
##
clean:
	@find . -type f \( \
		-name '*.o' ! -name 'FSTree.o' ! -name 'DirNode.o' \
		\) -exec rm -f {} \;
	@rm -f *~ a.out

# DO NOT DELETE
